CREATE TABLE [dbo].[Addresses]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [StreetAddress1] NVARCHAR(50) NOT NULL, 
    [StreetAddress2] NVARCHAR(50) NULL, 
    [City] NVARCHAR(30) NOT NULL, 
    [State] NVARCHAR(25) NOT NULL, 
    [ZipCode] NCHAR(6) NOT NULL, 
    [CustomerId] INT NOT NULL FOREIGN KEY REFERENCES dbo.[Customers]([Id]) ON DELETE CASCADE ON UPDATE CASCADE
)
