CREATE TABLE [dbo].[PhoneNumbers]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Number] NVARCHAR(15) NOT NULL, 
    [AddressId] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Addresses]([Id]) ON DELETE CASCADE ON UPDATE CASCADE
)
